[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_LINE_CHANNEL_ID = "2008606907"
  REACT_APP_LIFF_ID = "2008606907-O9j9wsuE"
  REACT_APP_LIFF_ID_C = "2009433243-uvLIAMqa"

[functions."scheduled-reminder"]
  schedule = "0 6 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
